# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRESS_USERNAME=NOT
export POSTGRESS_PASSWORD=NOT
export POSTGRESS_HOST=NOT
export POSTGRESS_DATABASE=NOT
export AWS_MEDIA_BUCKET=NOT
export AWS_REGION=NOT
export AWS_PROFILE=NOT
export JWT_SECRET=NOT
export URL=NOT
