apiVersion: v1
kind: Service
metadata:
  name: udagram-restapi-feeds
  labels:
    service: udagram-restapi-feeds
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-restapi-feeds