apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-restapi-feeds
  labels:
    app: udagram-restapi-feeds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-restapi-feeds
  template:
    metadata:
      labels:
        app: udagram-restapi-feeds
    spec:
      containers:
      - name: udagram-restapi-feeds
        image: augustocalado11/udagram-restapi-feeds
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80        
        env:
        - name: POSTGRESS_USERNAME
          value: "????????"
        - name: POSTGRESS_PASSWORD
          value: ""????????""
        - name: POSTGRESS_DATABASE
          value: "udagram"
        - name: POSTGRESS_HOST
          value: "udacityadiaz.cjvquh78n3mk.eu-west-3.rds.amazonaws.com"
        - name: AWS_REGION
          value: "eu-west-3"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_MEDIA_BUCKET
          value: "udagram-??????-dev"
        - name: JWT_SECRET
          value: "FJAEKFJLKSJEAKEKAJFFAIQOE"
